name: stream_nest
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  animated_notch_bottom_bar: ^1.0.3

  dio: ^5.9.0
  flashy_tab_bar2: ^0.0.10
  flutter:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  google_fonts: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  http: ^1.5.0
  path_provider: ^2.1.5
  provider: ^6.1.5
  tiktoklikescroller: ^0.2.8
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
